# Generated by Django 5.2.1 on 2025-05-26 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='Curso',
            new_name='curso',
        ),
        migrations.RenameField(
            model_name='avaliacao',
            old_name='Disciplina',
            new_name='disciplina',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='AreaSaber',
            new_name='area_saber',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='InstituicaoEnsino',
            new_name='instituicao_ensino',
        ),
        migrations.RenameField(
            model_name='cursodisciplina',
            old_name='Curso',
            new_name='curso',
        ),
        migrations.RenameField(
            model_name='cursodisciplina',
            old_name='Disciplina',
            new_name='disciplina',
        ),
        migrations.RenameField(
            model_name='cursodisciplina',
            old_name='Periodo',
            new_name='periodo',
        ),
        migrations.RenameField(
            model_name='disciplina',
            old_name='AreaSaber',
            new_name='area_saber',
        ),
        migrations.RenameField(
            model_name='frequencia',
            old_name='Curso',
            new_name='curso',
        ),
        migrations.RenameField(
            model_name='frequencia',
            old_name='Disciplina',
            new_name='disciplina',
        ),
        migrations.RenameField(
            model_name='frequencia',
            old_name='Pessoa',
            new_name='pessoa',
        ),
        migrations.RenameField(
            model_name='matricula',
            old_name='Curso',
            new_name='curso',
        ),
        migrations.RenameField(
            model_name='matricula',
            old_name='InstituicaoEnsino',
            new_name='instituicao_ensino',
        ),
        migrations.RenameField(
            model_name='matricula',
            old_name='Pessoa',
            new_name='pessoa',
        ),
        migrations.RenameField(
            model_name='ocorrencia',
            old_name='Curso',
            new_name='curso',
        ),
        migrations.RenameField(
            model_name='ocorrencia',
            old_name='Disciplina',
            new_name='disciplina',
        ),
        migrations.RenameField(
            model_name='ocorrencia',
            old_name='Pessoa',
            new_name='pessoa',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='AvaliacaoTipo',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='avaliacao_tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.avaliacaotipo', verbose_name='Tipo de avaliação: '),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.curso'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='turma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.turma'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='mae',
            field=models.CharField(max_length=100, verbose_name='Nome da Mãe:'),
        ),
    ]
