# Generated by Django 5.2.1 on 2025-05-26 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_turma_periodo_alter_disciplina_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='Curso: '),
        ),
        migrations.AddField(
            model_name='turma',
            name='turno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.turnos', verbose_name='Turno: '),
        ),
    ]
