# Generated by Django 5.2.1 on 2025-05-26 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_curso_avaliacao_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='Curso: '),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='turma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.turma', verbose_name='Turma: '),
        ),
    ]
